import { Modal } from '@heyforms/ui'
import party from 'party-js'
import { startTransition, useEffect, useMemo, useRef, useState } from 'react'

import { IconAI } from '~/components'
import { useBuilderContext, useMergeOptions } from '~/layout/builder3/context'
import { ProductService, SiteSettingsService } from '~/service'
import { useStore } from '~/store'
import { useVisible } from '~/utils'

export const Completions = () => {
  const { siteSettings } = useStore()
  const { state, dispatch } = useBuilderContext()
  const mergeOptions = useMergeOptions()

  const unfinished = useMemo(
    () => state.completions.filter(c => !siteSettings.completions.includes(c.name)),
    [siteSettings.completions, state.completions]
  )

  const [error, setError] = useState<string>()
  const loadingRef = useRef(false)

  const [visible, open, close] = useVisible()

  const selected = useMemo(
    () => state.completions.find(c => c.name === state.selectedCompletionName),
    [state.completions, state.selectedCompletionName]
  )

  async function handleCompletions(unfinished: any[]) {
    if (loadingRef.current || unfinished.length < 1) {
      return
    }

    setError(undefined)
    loadingRef.current = true

    const selected = unfinished[0]

    dispatch({
      type: 'updateState',
      payload: {
        selectedCompletionName: selected.name
      }
    })

    await ProductService.completions(siteSettings.productId, selected, {
      onMessage: data => {
        startTransition(() => {
          mergeOptions(selected.name, data[selected.name])
        })
      },
      onFinish: async (err?: string) => {
        loadingRef.current = false

        if (err) {
          setError(err)
        } else {
          unfinished.shift()
        }

        const unfinishedNames = unfinished.map(u => u.name)

        await SiteSettingsService.updateSettings(siteSettings.productId, {
          completions: state.completions
            .filter(c => !unfinishedNames.includes(c.name))
            .map(c => c.name)
        })

        if (unfinished.length > 0) {
          return handleCompletions(unfinished)
        }

        party.confetti(document.querySelector('.builder-editor') as HTMLElement, {
          count: [40, 80],
          speed: [800, 1_600]
        })

        dispatch({
          type: 'updateState',
          payload: {
            selectedCompletionName: undefined
          }
        })
      }
    })
  }

  function handleConfirm() {
    handleCompletions(unfinished)
    close()
  }

  useEffect(() => {
    // 新建 project
    if (siteSettings.version === 0) {
      handleCompletions(unfinished)
    }

    // 上次未完成 AI completions，询问用户是否继续
    else if (unfinished.length > 0) {
      open()
    }
  }, [])

  return (
    <>
      {selected && (
        <div className="absolute top-0 right-0 bottom-0 flex flex-col items-center justify-center w-[320px] min-[1400px]:w-[360px] 2xl:w-[480px] h-full bg-white border-l border-slate-200 z-10">
          <IconAI className="w-12 h-12 animate-pulse text-slate-400" />
          <div className="mt-4 text-sm">
            {error ? (
              <span className="text-red-600">{error}</span>
            ) : (
              <span className="text-slate-600">Generating for {selected.title}</span>
            )}
          </div>
        </div>
      )}

      <Modal.Confirm
        type="success"
        visible={visible}
        icon={<IconAI />}
        title="There are still some unfinished copies that have not been generated by AI."
        description="Would you like AI to continue generating the copies for you?"
        cancelLabel="Cancel"
        confirmLabel="Confirm"
        onCancel={close}
        onConfirm={handleConfirm}
      />
    </>
  )
}
